apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-media
  labels:
    {{- include "search-agent.componentLabels" (dict "root" $ "component" "api") | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.api.media.storageClassName }}
  storageClassName: {{ .Values.api.media.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.api.media.storage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-backups
  labels:
    {{- include "search-agent.componentLabels" (dict "root" $ "component" "api") | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.api.backups.storageClassName }}
  storageClassName: {{ .Values.api.backups.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.api.backups.storage }}
