# Generated by Django 6.0.4 on 2026-05-04 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sourcescope_result_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResultLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('normalized_name', models.CharField(max_length=180)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('place_type', models.CharField(blank=True, max_length=40)),
                ('importance', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name', 'latitude', 'longitude'],
            },
        ),
        migrations.RenameIndex(
            model_name='searchresult',
            new_name='core_search_topic_i_da863f_idx',
            old_name='core_search_topic_i_47911b_idx',
        ),
        migrations.RenameIndex(
            model_name='searchresult',
            new_name='core_search_domain_238327_idx',
            old_name='core_search_domain_cad20a_idx',
        ),
        migrations.RenameIndex(
            model_name='searchresult',
            new_name='core_search_publish_400258_idx',
            old_name='core_search_publish_8cdd22_idx',
        ),
        migrations.AddField(
            model_name='searchresult',
            name='location_signature',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='searchresultlocation',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.searchresult'),
        ),
        migrations.AddIndex(
            model_name='searchresultlocation',
            index=models.Index(fields=['normalized_name'], name='core_search_normali_b11e8e_idx'),
        ),
        migrations.AddIndex(
            model_name='searchresultlocation',
            index=models.Index(fields=['latitude', 'longitude'], name='core_search_latitud_172a9c_idx'),
        ),
        migrations.AddConstraint(
            model_name='searchresultlocation',
            constraint=models.UniqueConstraint(fields=('result', 'normalized_name', 'latitude', 'longitude'), name='unique_result_location_per_result'),
        ),
    ]
