# Generated by Django 6.0.6 on 2026-06-21 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_savedfolder_searchresult_folder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='searchresult',
            name='unique_result_per_topic_url',
        ),
        migrations.AddField(
            model_name='searchresult',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.searchtopic'),
        ),
        migrations.AddConstraint(
            model_name='searchresult',
            constraint=models.UniqueConstraint(condition=models.Q(('topic__isnull', False)), fields=('topic', 'normalized_url'), name='unique_result_per_topic_url'),
        ),
        migrations.AddConstraint(
            model_name='searchresult',
            constraint=models.UniqueConstraint(condition=models.Q(('topic__isnull', True)), fields=('owner', 'normalized_url'), name='unique_bookmark_per_owner_url'),
        ),
    ]
