# Generated by Django 6.0.6 on 2026-09-06 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_topictimelinesummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='summary_signature',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='searchtopic',
            name='category_terms',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='searchtopic',
            name='include_in_press_review',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='searchtopic',
            name='origin_kind',
            field=models.CharField(choices=[('manual', 'Manual'), ('followed', 'Followed')], default='manual', max_length=16),
        ),
        migrations.AddField(
            model_name='searchtopic',
            name='origin_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_topics', to='core.searchresult'),
        ),
    ]
